site_name: Pollen Documentation
site_url: https://givensuman.github.io/pollen
repo_url: https://github.com/givensuman/pollen
repo_name: givensuman/pollen
site_description: Official documentation for Pollen, a friendly dotfile manager.
theme:
  name: shadcn
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Commands: commands.md
  - Configuration: configuration.md
  - Directory Structure: directory_structure.md
  - Git Integration: git_integration.md
  - Dependency Management: dependency_management.md
  - Environment Variables: environment_variables.md
  - License: license.md
